name: University News
on:
  schedule:
    - cron: 0 10,19 * * *
  workflow_dispatch:

env:
  NEWS_URL: ${{secrets.NEWS_URL}}
  DISCORD_WEBHOOK: ${{secrets.DISCORD_WEBHOOK}}

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build typescript code"
    permissions:
      contents: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
      - name: "Setup nodejs"
        uses: actions/setup-node@v6
        with:
          node-version: 20
      - name: Install deps
        run: npm ci
      - name: Build code
        run: npm run build
      - name: Fetch and check news
        run: npm run start
      - name: Commit hash file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add last-hash
          git diff --staged --quiet || git commit -m "Update news hash"
          git push
